FROM markdegroot/unifi-protect-arm64:latest

# this is just a patch to prevent the unifi-core service stopping every 2 minutes because it hits the systemd timeout
RUN sed -i -e 's/WatchdogSec/#WatchdogSec/g' /lib/systemd/system/unifi-core.service \
 && sed -i -e 's/Type=notify/Type=simple/g' /lib/systemd/system/unifi-core.service
