#!/bin/bash

if [ "$1" == "id" ]; then

    if [ ! -f /data/uuid.txt ]; then
        cat /proc/sys/kernel/random/uuid > /data/uuid.txt
    fi
    uuid=$(cat /data/uuid.txt)
    serial=$(cat /sys/class/net/$(ip route get 8.8.8.8 | grep -Po '(?<=(dev ))(\S+)')/address | sed 's/://g')

    # echo "board.sysid=0xb719" # UVC_NVR
    # echo "board.sysid=0xe970" # UCK_G2_PLUS
    # echo "board.sysid=0xea13" # UDM_SE
    # echo "board.sysid=0xea15" # UDM_PRO
    echo "board.sysid=0xea16" # UNVR4
    # echo "board.sysid=0xea1a" # UNVR4
    # echo "board.sysid=0xea20" # UNVR_PRO
    # echo "board.sysid=0xffff" # MAC_OS

    echo "board.uuid=$uuid"
    echo "board.name=UniFi Network Video Recorder"
    echo "board.shortname=UNVR"
    echo "board.hwrev=1"
    echo "board.serialno=$serial"
fi
